resources:
  - name: runVariableResource
    type: PropertyBag
    configuration:
      testRunVariable: test

pipelines:
  
  - name: S_WF_033runVariable
    steps:
  
      - name: S_WF_033_001bash
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: S_WF_033_002bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
        execution:
          onStart:
            - add_run_variables step_2_var="onStart"
          onExecute:
            - echo "Step 2 is running"
            - add_run_variables step_2_varOnExecute="onExecute"
          onComplete:
            - add_run_variables step_2_varOnComplete="onComplete"
  
      - name: S_WF_033_003bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
        execution:
          onExecute:
            - echo "Step 3 is running"
  
      - name: S_WF_033_004bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_4_var="step4"
          onExecute:
            - echo "Step 4 is running"
  
      - name: S_WF_033_005bas
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_002bash
            - name: S_WF_033_004bash
          affinityGroup: some_ag
        execution:
          onStart:
            - if [[ "$step_2_var" != "onStart" ]]; then echo "variable does not match expected value"; fi
            - if [[ "$step_4_var" != "step4" ]]; then echo "variable does not match expected value"; fi
            - if [[ "$step_2_varOnExecute" != "onExecute" ]]; then echo "variable does not match expected value"; fi
            - if [[ "$step_2_varOnComplete" != "onComplete" ]]; then echo "variable does not match expected value"; fi
          onExecute:
            - echo "Step 5 is running"
            - echo "step_2_var - ${step_2_var}"
            - echo "step_4_var - ${step_4_var}"
            - echo step_2_varOnExecute=$step_2_varOnExecute
            - echo step_2_varOnComplete=$step_2_varOnComplete
            - if [[ "$step_2_var" != "onStart" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_4_var" != "step4" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnExecute" != "onExecute" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnComplete" != "onComplete" ]]; then echo "variable does not match expected value"; else exit 1; fi
  
      - name: S_WF_033_006bas
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_005bas
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "Step 6 is running"
            - if [[ "$step_2_var" != "onStart" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_4_var" != "step4" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnExecute" != "onExecute" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnComplete" != "onComplete" ]]; then echo "variable does not match expected value"; else exit 1; fi
          onComplete:
            - echo "Step 6 is running"
            - if [[ "$step_2_var" != "onStart" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_4_var" != "step4" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnExecute" != "onExecute" ]]; then echo "variable does not match expected value"; else exit 1; fi
            - if [[ "$step_2_varOnComplete" != "onComplete" ]]; then echo "variable does not match expected value"; else exit 1; fi

  - name: runVariablePipeline
    steps:
  
      - name: step1arv
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: step2arv
        type: Bash
        configuration:
          inputSteps:
            - name: step1arv
        execution:
          
          onExecute:
            - echo "Step 2 is running"
  
      - name: step3arv
        type: Bash
        configuration:
          inputSteps:
            - name: step1arv
        execution:
          onStart:
            - add_run_variables testStep3onStart="col2"
          onExecute:
            - echo "Step 3 is running"
  
      - name: step4arv
        type: Bash
        configuration:
          inputSteps:
            - name: step3arv
          affinityGroup: testarv
        execution:
          onExecute:
            - add_run_variables testStep4="col3"
            
      - name: step5arv
        type: Bash
        configuration:
          outputResources:
            - name: runVariableResource
          inputSteps:
            - name: step4arv
          affinityGroup: testarv
        execution:
          onExecute:
            - echo "Step 5 is running"
            - echo "testStep4 - ${testStep4}"
            - echo "testStep3onStart - ${testStep3onStart}"
            - if [ "$testStep4" != "col3" ]; then echo "variable does not match expected value"; else exit 1; fi
            - if [ "$testStep3onStart" != "col2" ]; then echo "variable does not match expected value"; else exit 1; fi
            - write_output runVariableResource "testRunVariable=updated"
  
      - name: step6arv
        type: Bash
        configuration:
          inputResources:
            - name: runVariableResource
          affinityGroup: testarv1
        execution:
          onExecute:
            - echo "Step 6 is running"
            - echo "testStep4 - ${testStep4}"
            - echo "testStep3onStart - ${testStep3onStart}"
            - if [ "$testStep4" != "col3" ]; then echo "variable does not match expected value"; else exit 1; fi
            - if [ "$testStep3onStart" != "col2" ]; then echo "variable does not match expected value"; else exit 1; fi
            - echo $res_runVariableResource_testRunVariable
            - if [ "$res_runVariableResource_testRunVariable" != "updated" ]; then echo "variable does not match expected value"; else exit 1; fi  
