pipelines:
  
  - name: S_WF_033bash
    steps:
  
      - name: S_WF_033_001bash
        type: Bash
        execution:
          onExecute:
            - echo "Step 1 is running"
  
      - name: S_WF_033_002bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
        execution:
          onStart:
            - add_run_variables step_2_var="step2"
          onExecute:
            - echo "Step 2 is running"
  
      - name: S_WF_033_003bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
        execution:
          onExecute:
            - echo "Step 3 is running"
  
      - name: S_WF_033_004bash
        type: Bash
        configuration:
          inputSteps:
            - name: S_WF_033_001bash
          affinityGroup: some_ag
        execution:
          onStart:
            - add_run_variables step_4_var="step4"
          onExecute:
            - echo "Step 4 is running"
  
      - name: S_WF_033_005bash
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_033_002bash
            - name: S_WF_033_004bash
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "Step 5 is running"
            - echo "step_2_var - ${step_2_var}"
            - echo "step_4_var - ${step_4_var}"
            - if ["$step_2_var" === "step2"] then echo "variable does not match expected value"
            - if ["$step_4_var" === "step4"] then echo "variable does not match expected value" }
  
      - name: S_WF_033_006bash
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_WF_033_005bash
          affinityGroup: some_ag
        execution:
          onExecute:
            - echo "Step 6 is running"
