pipelines:
  - name: approval_gate_member_chronology_pipeline
    steps:
      - name: approval_gate_step1
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - member
#           chronological: true
        execution:
          onStart:
            - echo "test"
          onExecute:
            - printenv
            
      - name: approval_gate_step2
        type: Bash
        configuration:
          chronological: true
          inputSteps:
            - name: approval_gate_step1
        execution:
          onExecute:
            - printenv
            
  - name: admin_approval_pipeline
    steps:
      - name: admin_approval_gate_step1
        type: Bash
        configuration:
          
        execution:
          onStart:
            - echo "test"
          onExecute:
            - printenv
            
      - name: admin_approval_gate_step2
        type: Bash
        configuration:
          requiresApproval:
            approvers:
              - admin
          inputSteps:
            - name: admin_approval_gate_step1
        execution:
          onExecute:
            - printenv
