resources:
  - name: gitRepo_push_image_artifactory
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/run_adjacency
      branches:  # optional
        include: master

  - name: imageBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: s_artifactory
      buildName: jfreqCustomImg
      buildNumber: ${run_id}

pipelines:
  - name: buildAndPushCustomImageToArtifactory
    configuration:
      jfrogCliVersion: 2
    steps:
      - name: custom_image_build_push
        type: Bash
        configuration:
          affinityGroup: imageBuildPush
          environmentVariables:
            SKIP_DOCKER_RESOURCES_CLEANUP: "true"
          integrations:
            - name: s_artifactory
          inputResources:
            - name: gitRepo_push_image_artifactory
          outputResources:
            - name: imageBuildInfo
        execution:
          onStart:
            - artifactory_registry_url=$(echo "$int_s_artifactory_url" | sed 's#.*//\([^/]*\)/.*#\1#')
            - add_run_variables artifactory_registry_url="$artifactory_registry_url"
            - echo $artifactory_registry_url
          onExecute:
            - task: jfrog/docker-build@v0.0.1
              repository: pipelines-tasks-virtual
              input:
                resourceName: gitRepo_push_image_artifactory
                dockerImage: "$artifactory_registry_url/example-repo-local/jfreqCustomImg:${RUN_NUMBER}"
                dockerFileName: Dockerfile
                dockerFileLocation: .
            - task: jfrog/docker-push@v0.0.2
              repository: pipelines-tasks-virtual
              input:
                dockerImage: "$artifactory_registry_url/example-repo-local/jfreqCustomImg:${RUN_NUMBER}"
                autoPublishBuildInfo: "true"
                outputBuildInfoResourceName: "imageBuildInfo"
          onFailure:
            - stepCommons_on_failure
          onSuccess:
            - stepCommons_on_success
          onComplete:
            - stepCommons_on_complete

      - name: custom_image_from_artifactory_step
        type: Bash
        configuration:
          inputResources:
            - name: imageBuildInfo
          affinityGroup: imageBuildPush
          runtime:
            type: image
            image:
              custom:
                registry: s_artifactory
                name: $artifactory_registry_url/example-repo-local/jfreqCustomImg
                tag: ${RUN_NUMBER}
                autoPull: true
        execution:
          onExecute:
            - printenv
            - echo $step_image_name
            - echo $step_image_tag
            - echo $image_tag
            - echo $artifactory_registry_url
            # -  if ! [[ "$step_image_name" =~ "example-repo-local/jfreq" ]]; then return 1; fi
