pipelines:
  - name: chronology_pipeline #make sure you have more than 1 node
    configuration:
      chronological: true
    steps:
      - name: chronological_step1
        type: Bash
        configuration:
          environmentVariables:
            BRANCH_NAME: test
        execution:
          onStart:
            - echo $BRANCH_NAME
          onExecute:
            - printenv
