pipelines:


  - name: pipelineConditionWorkflowAllowFailure
    steps:
      - name: allfailure1step
        type: Bash
        execution:
          onExecute:
            - echo "executing step..."
            - add_run_variables "key=value"
            - failure ok

      - name: allfailure2step
        type: Bash
        configuration:
          allowFailure: true
          environmentVariables:
              new_env:
                default: 2
          condition: 'new_env == 2'
          inputSteps:
            - name: allfailure1step
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
            

  - name: pipelineConditionVariable
    steps:
      - name: cv1step
        type: Bash
        execution:
          onExecute:
            - echo "executing step..."
            - add_run_variables "key=value"

      - name: cv2step
        type: Bash
        configuration:
          environmentVariables:
              new_env:
                default: 2
          condition: 'new_env == 2'
          inputSteps:
            - name: cv1step
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
            
      - name: cv3step
        type: Bash
        configuration:
          condition: 'key == "value"'
          inputSteps:
            - name: cv1step
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
