pipelines:

  - name: pipelineConditionVariable
    steps:
      - name: cv1step
        type: Bash
        execution:
          onExecute:
            - echo "executing step..."
            - add_run_variables "key=1"

      - name: cv2step
        type: Bash
        configuration:
          condition: key == 1
          inputSteps:
            - name: cv1step
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
            
      - name: cv3step
        type: Bash
        configuration:
          inputSteps:
            - name: cv2step
        execution:
          onExecute:
            - echo "executing step..."
            - echo $key
            - sleep 10
