resources:
  - name: S_Bash_Generic_5858_0010
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: jfbetapipeorg/Org_test_Automation
      
pipelines:
  - name: Pipeline_S_Bash_Generic_5858_0010
    steps:
      - name: Step_S_Bash_Generic_5858_0010_1
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_Generic_5858_0010
        execution:
          onExecute:
            - echo "executing Step_S_Bash_Generic_5858_0010_1"
            - sleep 60

      - name: Step_S_Bash_Generic_5858_0010_2
        type: Bash
        configuration:
          inputSteps:
            - name: Step_S_Bash_Generic_5858_0010_1
              status:
                - timeout
        execution:
          onExecute:
            - echo "executing Step_S_Bash_Generic_5858_0010_2"
