pipelines:
  - name: test_matrix
    steps:
      - name: preMatrixTest
        type: PreMatrix
        execution:
          onExecute:
            - mkdir -p preState
            - echo "working" >> preState/working.txt
            - echo ${steplet_id}
            - add_run_variable preMatrixStepletId ${steplet_id}
            
      - name: matrixStep
        type: Matrix
        configuration:
          inputSteps:
            - name: preMatrixTest
        stepletMultipliers:
          environmentVariables:
            - name: test
              name2: test2
            - type: step
              type2: step2
        execution:
          onExecute:
            - ls -latr .
            - ls -latr preMatrixTest/preState
            - mkdir -p matrixFiles/${steplet_id}
            - echo "working" >> matrixFiles/${steplet_id}/working.txt
            - echo ${steplet_id}
            - add_run_variable matrixStepletId ${steplet_id}
           
      - name: postMatrixTest
        type: PostMatrix
        configuration:
          inputSteps:
            - name: matrixStep
        execution:
          onExecute:
            - ls -latr
            - ls -latr matrixStep
            - ls -latr matrixStep/matrixFiles/$matrixStepletId
            - cat matrixStep/matrixFiles/$matrixStepletId/working.txt
            - echo ${steplet_id}
            - if [ -f "$File" ]; then  echo "$File exist"  else  echo "$File does not exist"  fi  
