resources:
  - name: connect_too_many_steps
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
  - name: res_output
    type: PropertyBag
    configuration:
      test: ''
      
pipelines:

  - name: multiParallelAndSeriesStepsPipeline
    configuration:
      environmentVariables:
        readOnly: 
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    steps:
      - name: oneCol_step1
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: node
                versions:
                  - '16'
          environmentVariables:
            key1: "value1"
            key2: "value2"
            key3: "value3"
          affinityGroup: ag_group1
        execution:
          onExecute:
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $key1
            - echo $key2
            - echo $key3
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: twoCol_step1
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - '11'
          affinityGroup: ag_group1
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                       
      - name: twoCol_step2
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - '13'
          inputSteps:
            - name: oneCol_step1
          outputResources:
            - name: res_output
          affinityGroup: ag_group1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO   
            - write_output res_output test=$commitSha runID=$current_runid
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: twoCol_step3
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
          affinityGroup: ag_group1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                        
      - name: twoCol_step4
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                                    
      - name: twoCol_step5
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: threeCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: res_output
          affinityGroup: ag_group2
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: threeCol_step2
        type: Bash
        configuration:
          inputResources:
            - name: res_output
          affinityGroup: ag_group2
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                    
      - name: threeCol_step3
        type: Bash
        configuration:
          inputResources:
            - name: res_output
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO 
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                                
      - name: fourCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inputSteps:
            - name: threeCol_step1
            - name: threeCol_step2
          affinityGroup: ag_group2
        execution:
          onExecute:
            - printenv
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: fiveCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inputSteps:
            - name: fourCol_step1
          affinityGroup: ag_group3
        execution:
          onExecute:
            - printenv
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                        
      - name: sixCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inputSteps:
            - name: fiveCol_step1
          affinityGroup: ag_group3
        execution:
          onExecute:
            - printenv
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
                             
      - name: sixCol_step2
        type: Bash
        configuration:
          inputSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
      
      - name: sixCol_step3
        type: Bash
        configuration:
          inputSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: sixCol_step4
        type: Bash
        configuration:
          inputSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
          
      - name: sixCol_step5
        type: Bash
        configuration:
          inputSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
            
      - name: sevenCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inputSteps:
            - name: sixCol_step1
          affinityGroup: ag_group3
        execution:
          onExecute:
            - printenv 
            - echo stepNodeId=$step_node_id stepNodeName=$step_node_name
              
            
            
            
            
            
