resources:
  - name: connect_too_many_steps
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
  - name: res_output
    type: PropertyBag
    configuration:
      test: ''
      
pipelines:

  - name: multiParallelAndSeriesStepsPipeline
    configuration:
      environmentVariables:
        readOnly: 
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    steps:
      - name: oneCol_step1
        type: Bash
        configuration:
          environmentVariables:
            key1: "value1"
            key2: "value2"
            key3: "value3"
        execution:
          onExecute:
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $key1
            - echo $key2
            - echo $key3
            
      - name: twoCol_step1
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
                       
      - name: twoCol_step2
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
          outputResources:
            - name: res_output
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO   
            - write_output res_output test=$commitSha runID=$current_runid
            
      - name: twoCol_step3
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
                        
      - name: twoCol_step4
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
                                    
      - name: twoCol_step5
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
                                         
      - name: threeCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: res_output
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
            
      - name: threeCol_step2
        type: Bash
        configuration:
          inputResources:
            - name: res_output
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
                    
      - name: threeCol_step3
        type: Bash
        configuration:
          inputResources:
            - name: res_output
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO 
            - sleep 30s
                                
      - name: fourCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inoutSteps:
            - name: threeCol_step1
            - name: threeCol_step2
        execution:
          onExecute:
            - printenv
            
      - name: fiveCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inoutSteps:
            - name: fourCol_step1
        execution:
          onExecute:
            - printenv
                        
      - name: sixCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inoutSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
                             
      - name: sixCol_step2
        type: Bash
        configuration:
          inoutSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
      
      - name: sixCol_step3
        type: Bash
        configuration:
          inoutSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            
      - name: sixCol_step4
        type: Bash
        configuration:
          inoutSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
          
      - name: sixCol_step5
        type: Bash
        configuration:
          inoutSteps:
            - name: fiveCol_step1
        execution:
          onExecute:
            - printenv
            - sleep 30s
            
      - name: sevenCol_step1
        type: Bash
        configuration:
          inputResources:
            - name: connect_too_many_steps
          inoutSteps:
            - name: sixCol_step1
        execution:
          onExecute:
            - printenv 
              
            
            
            
            
            
