pipelines:
  - name: priorityAndAffinityGroupsPipeline
    steps:

      - name: pag_step_001
        type: Bash
        execution:
          onExecute:
            - echo "step 1 is running"

      - name: pag_step_004
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 4
        execution:
          onExecute:
            - echo "step 2 is running"

      - name: pag_step_002
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 1
        execution:
          onExecute:
            - echo "step 3 is running"

      - name: pag_step_003
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_001
          affinityGroup: ag_group1
          priority: 3
        execution:
          onExecute:
            - echo "step 4 is running"

      - name: pag_step_006
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_002
            - name: pag_step_003
            - name: pag_step_004
          affinityGroup: ag_group1
          priority: 2
        execution:
          onExecute:
            - echo "step 5 is running"

      - name: pag_step_005
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_002
            - name: pag_step_003
            - name: pag_step_004
          affinityGroup: ag_group1
          priority: 1
        execution:
          onExecute:
            - echo "step 6 is running"

      - name: pag_step_007
        type: Bash
        configuration:
          inputSteps:
            - name: pag_step_005
            - name: pag_step_006
          affinityGroup: ag_group1
          priority: 2
        execution:
          onExecute:
            - echo "step 7 is running"
