pipelines:
  - name: S_Bash_9439_0001test
    steps:
      - name: S_Bash_9439_0001_steptest
        type: Bash
        execution:
          onExecute:
            - printenv
            - echo "${pipelines_api_url}"
            - echo "$pipelines_api_url"
            - curl -H "Authorization:Bearer ${builder_api_token}" -H "Content-type:application/json" "${pipelines_api_url}/projectIntegrations/14" -o int.json
            - intToken=\$(cat int.json | jq -r '.formJSONValues | .[] | select(.label=="token") | .value')
            - if [[ "$intToken" != "********" ]]; then exit 1; fi
                     
