pipelines:
                - name: ${testName}
                  steps:
                    - name: S_Matrix_S_4898_0002
                      type: Matrix
                      stepMode: Bash
                      configuration:
                        multiNode: true
                        nodePool: TEST_NODEPOOL_4898
                      stepletMultipliers:
                        environmentVariables:
                          - foo: "foo"
                          - foo: "bar"
                        runtimes:
                          - type: image
                            image:
                              auto:
                                language: node
                                versions:
                                  - 12.14.0
                      execution:
                        onExecute:
                          - echo $foo
