pipelines:
  - name: successPipeline
    configuration:
      environmentVariables:
        readOnly:
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    steps:
      - name: successStep1
        type: Bash
        execution:
          onExecute:
            - printenv
      - name: successStep2
        type: Bash
        configuration:
          inputSteps:
            - name: successStep1
        execution:
          onExecute:
            - printenv

  - name: timeoutPipeline
    
    steps:
      - name: timeOutStep1
        type: Bash
        execution:
          onExecute:
            - printenv
            
      - name: timeOutStep
        type: Bash
        configuration:
          timeoutSeconds: 10
          inputSteps:
            - name: timeOutStep1
        execution:
          onExecute:
            - printenv
            - sleep 10m
  
#   - name: errorPipeline
#     steps:
#       - name: errorStep
#         type: Bash
#         execution:
#           onExecute:
#             - printenv
              
  - name: failurePipeline
    steps:
      - name: failureStep1
        type: Bash
        execution:
          onExecute:
            - printenv
            
      - name: failureStep
        type: Bash
        configuration:
          inputSteps:
            - name: failureStep1
        execution:
          onExecute:
            - printenv332@!@#@#!#!#!#!#!
