pipelines:
  - name: timeoutStepLevel
    
    steps:
      - name: firstStep
        type: Bash
        execution:
          onExecute:
            - printenv
            
      - name: timeOutStep12
        type: Bash
        configuration:
          timeoutSeconds: 150
          inputSteps:
            - name: timeOutStep11
        execution:
          onExecute:
            - printenv
            - sleep 10m

      - name: timeOutSystemLevel
        type: Bash
        configuration:
          inputSteps:
            - name: timeOutStep11
        execution:
          onExecute:
            - printenv
            - sleep 150m
            
  - name: timeoutNodePoolLevel
    steps:
      - name: timeOutStepnodePoolLevel
        type: Bash
        execution:
          onExecute:
            - printenv
            - sleep 75m
