pipelines:
  - name: timeoutStepLevel
    
    steps:
      - name: firstStep
        type: Bash
        execution:
          onExecute:
            - printenv
            
      - name: timeOutStep12
        type: Bash
        configuration:
          timeoutSeconds: 150
          inputSteps:
            - name: firstStep
        execution:
          onExecute:
            - printenv
            - sleep 10m

      - name: timeOutDefaultSystemTimeout
        type: Bash
        configuration:
          nodePool: testtimeout
          inputSteps:
            - name: firstStep
        execution:
          onExecute:
            - printenv
            - sleep 300m
            
      - name: timeOutStepMoreThanDefaultNodePool
        type: Bash
        configuration:
          timeoutSeconds: 4000
          inputSteps:
            - name: firstStep
        execution:
          onExecute:
            - printenv
            - sleep 100m

      - name: timeOutLessThanSystemLevel
        type: Bash
        configuration:
          nodePool: testtimeout
          timeoutSeconds: 6000
          inputSteps:
            - name: firstStep
        execution:
          onExecute:
            - printenv
            - sleep 150m
            
      - name: timeOutMoreThanSystemLevel
        type: Bash
        configuration:
          nodePool: testtimeout
          timeoutSeconds: 8000
          inputSteps:
            - name: firstStep
        execution:
          onExecute:
            - printenv
            - sleep 150m
            
  - name: timeoutNodePoolLevel
    steps:
      - name: timeOutStepnodePoolLevel
        type: Bash
        execution:
          onExecute:
            - printenv
            - sleep 75m
