resources:
  - name: myupdatecommitstatusGitRepo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/sample_python
      branches:
        include: main
  
pipelines:
  - name: updatecommitstatusPipe
    steps:
      - name: updatecommitstatusStep
        type: Bash
        configuration:
          inputResources:
            - name: myupdatecommitstatusGitRepo
        execution:
          onStart:
            - update_commit_status myupdatecommitstatusGitRepo --status processing --message "marked as processing" 
          onExecute:
            - update_commit_status myupdatecommitstatusGitRepo --status success --message "marked as success" 
