resources:
  - name: WONParentComplete_resource
    type: PropertyBag
    configuration:
      test: test

  - name: dependencyModeRepo
    type: GitRepo
    configuration:
      gitProvider: varsha_github
      path: Varsha-Arun/simple
      branches:
        include: main

pipelines:
  - name: A_parent
    steps:  
      - name: createImage
        type: Bash
        configuration:
          inputResources:
            - name: dependencyModeRepo
          outputResources:
            - name: WONParentComplete_resource
        execution:
          onExecute:
            - write_output WONParentComplete_resource test=${run_number}
            - tdcdadad

  - name: A_waitOnParent
    configuration:
      dependencyMode:
        waitOnParentComplete: true
    steps:  
      - name: A_waitOnParentStep
        type: Bash
        configuration:
          inputResources:
            - name: WONParentComplete_resource
        execution:
          onExecute:
            - echo ${res_WONParentComplete_resource_test}
